//
//  MessagesViewController.swift
//  MessagesExtension
//
//  Created by alexei on 9/9/16.
//  Copyright © 2016 zelig. All rights reserved.
//

import UIKit
import Messages
import StoreKit

class MessagesViewController: MSMessagesAppViewController, SKProductsRequestDelegate, SKPaymentTransactionObserver {
    var purchasedProductIDs = [String]()
    var productsArray = [SKProduct]()

    var stickerNames = [
        "bieber": ["Bieber1", "Bieber2", "Bieber3"],
        "bernie": ["Bernie1", "Bernie2"],
        "drake": ["Drake1", "Drake2", "Drake3", "Drake4", "Drake5"],
        "chance": ["Beiber1", "Beiber2", "Beiber3"],
        "beyonce": ["Bernie1", "Bernie2"]
    ]
    
    var selectedProductIndex: Int!
    var transactionInProgress = false
    
    @IBOutlet var collectionView: UICollectionView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        requestProductInfo()
        
        SKPaymentQueue.default().add(self)
    }
    
    func requestProductInfo() {
        if SKPaymentQueue.canMakePayments() {
            let productRequest = SKProductsRequest(productIdentifiers: Set(stickerNames.keys))
            
            productRequest.delegate = self
            productRequest.start()
        } else {
            print("Cannot perform In App Purchases.")
        }
    }
    
    func productsRequest(_ request: SKProductsRequest, didReceive response: SKProductsResponse) {
        if response.products.count != 0 {
            for product in response.products {
                productsArray.append(product)
                
                let purchased = UserDefaults.standard.bool(forKey: product.productIdentifier)
                if purchased {
                    purchasedProductIDs.append(product.productIdentifier)
                }
                
            }
            collectionView.reloadData()
        } else {
            print("There are no products.")
        }
        
        if response.invalidProductIdentifiers.count != 0 {
            print(response.invalidProductIdentifiers.description)
        }
    }
    
    func paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {
        for transaction in transactions {
            switch transaction.transactionState {
            case .purchased:
                print("Transaction completed successfully.")
                SKPaymentQueue.default().finishTransaction(transaction)
                purchasedProductIDs.append(productsArray[selectedProductIndex].productIdentifier)
                transactionInProgress = false
            case .failed:
                print("Transaction Failed")
                SKPaymentQueue.default().finishTransaction(transaction)
                transactionInProgress = false
            default:
                print(transaction.transactionState.rawValue)
            }
        }
    }
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }
}

extension MessagesViewController: UICollectionViewDataSource, UICollectionViewDelegate {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return productsArray.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "collectionViewCell", for: indexPath) as! CollectionViewCell
        
        cell.imageView.image = UIImage(named: productsArray[indexPath.row].productIdentifier)
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if transactionInProgress {
            return
        }
        
        selectedProductIndex = indexPath.row
        
        if purchasedProductIDs.contains(productsArray[selectedProductIndex].productIdentifier) {
            showStickerBrowser(index: indexPath.row)
        } else {
            let payment = SKPayment(product: productsArray[selectedProductIndex])
            SKPaymentQueue.default().add(payment)
            transactionInProgress = true
        }
    }
    
    func showStickerBrowser(index: Int) {
        let stickerBrowserVC = UIStoryboard(name: "MainInterface", bundle: nil).instantiateViewController(withIdentifier: "StickerBrowserViewController") as! StickerBrowserViewController
        stickerBrowserVC.packName = productsArray[index].productIdentifier
        stickerBrowserVC.stickerNames = stickerNames[productsArray[index].productIdentifier]!
        self.present(stickerBrowserVC, animated: false, completion: nil)
    }
}
